SELECT CustomerID, 
    COUNT(PRODUCTID) AS NUM_PRODUCTS,
    SUM(NUMBEROFUSERS) AS TOTAL_USERS,
    CASE WHEN (COUNT(PRODUCTID) = 1 OR SUM(NUMBEROFUSERS) >= 5000) THEN 1 
        ELSE 0
        END AS UPSELL_OPPORTUNITY
FROM Subscriptions 
GROUP BY CustomerID